[[YASM]]
arch = "aarch64"
git-tree-sha1 = "221c298fc659a9c707a9f7b84f93c9c0d6fb4af3"
os = "macos"

    [[YASM.download]]
    sha256 = "df939ac3cd0e6140bb193c10aa1bf4023368c48631d5cb90c79547b1e3a9b008"
    url = "https://github.com/JuliaBinaryWrappers/YASM_jll.jl/releases/download/YASM-v1.3.0+1/YASM.v1.3.0.aarch64-apple-darwin.tar.gz"
[[YASM]]
arch = "aarch64"
git-tree-sha1 = "08123c1c383cef235d50ff1fbd8f5e47065be0ad"
libc = "glibc"
os = "linux"

    [[YASM.download]]
    sha256 = "5aaa705026946336399e935aa419365d692326a325a706b2389f338a15adeff7"
    url = "https://github.com/JuliaBinaryWrappers/YASM_jll.jl/releases/download/YASM-v1.3.0+1/YASM.v1.3.0.aarch64-linux-gnu.tar.gz"
[[YASM]]
arch = "aarch64"
git-tree-sha1 = "e2f6b0e8171e1e7c24ae325aae542fb791e331f3"
libc = "musl"
os = "linux"

    [[YASM.download]]
    sha256 = "d2cbad7f92daf8ddc878e7c40e19a3e0d36c55faeeadaba7741263b76a4f40a6"
    url = "https://github.com/JuliaBinaryWrappers/YASM_jll.jl/releases/download/YASM-v1.3.0+1/YASM.v1.3.0.aarch64-linux-musl.tar.gz"
[[YASM]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "37555c0bd1a37615a9c0ed03981d897a1370ab34"
libc = "glibc"
os = "linux"

    [[YASM.download]]
    sha256 = "38207b3e14c0d4857ebc64eaa9890e10880ee20f105b915d5dd0c1ee680eefda"
    url = "https://github.com/JuliaBinaryWrappers/YASM_jll.jl/releases/download/YASM-v1.3.0+1/YASM.v1.3.0.armv6l-linux-gnueabihf.tar.gz"
[[YASM]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "fac6ad8b24221315a8d1dcf2871ae6354a7c6f75"
libc = "musl"
os = "linux"

    [[YASM.download]]
    sha256 = "5dcfcfdc58e9aa92f7de8e03b4f3d22e967b7668e380009260322a7d5c1e2f85"
    url = "https://github.com/JuliaBinaryWrappers/YASM_jll.jl/releases/download/YASM-v1.3.0+1/YASM.v1.3.0.armv6l-linux-musleabihf.tar.gz"
[[YASM]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "4e3f6326a4a83a43e9c17f8508eb5db392417636"
libc = "glibc"
os = "linux"

    [[YASM.download]]
    sha256 = "d482ada48253d5a067ef787c58a228142e98da77776fb5dfa1753bffae36e7e3"
    url = "https://github.com/JuliaBinaryWrappers/YASM_jll.jl/releases/download/YASM-v1.3.0+1/YASM.v1.3.0.armv7l-linux-gnueabihf.tar.gz"
[[YASM]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "1bf205c6401c0e46675cc02c1f3e99fb8f2b4996"
libc = "musl"
os = "linux"

    [[YASM.download]]
    sha256 = "9647ef8ec56b6e24d8f37dfa067bdc569f0988007984b340336ceae7aacf4a06"
    url = "https://github.com/JuliaBinaryWrappers/YASM_jll.jl/releases/download/YASM-v1.3.0+1/YASM.v1.3.0.armv7l-linux-musleabihf.tar.gz"
[[YASM]]
arch = "i686"
git-tree-sha1 = "ff4dc4fe53ad16b85249c44dd61b8e70572f1eec"
libc = "glibc"
os = "linux"

    [[YASM.download]]
    sha256 = "ca6ca4a08f851a0c9d21052b900d1c861f81c3928e8dcfdd885c4e200f35f7db"
    url = "https://github.com/JuliaBinaryWrappers/YASM_jll.jl/releases/download/YASM-v1.3.0+1/YASM.v1.3.0.i686-linux-gnu.tar.gz"
[[YASM]]
arch = "i686"
git-tree-sha1 = "2a2e3dcd1cdc50c8fb606a6dc7bbf17332293774"
libc = "musl"
os = "linux"

    [[YASM.download]]
    sha256 = "c107380f020ad80ade429e32a28ad24232c25fb246990a676f10bc271beab454"
    url = "https://github.com/JuliaBinaryWrappers/YASM_jll.jl/releases/download/YASM-v1.3.0+1/YASM.v1.3.0.i686-linux-musl.tar.gz"
[[YASM]]
arch = "i686"
git-tree-sha1 = "fffcd7c76591974b6a9611d38368d26ad3bc331f"
os = "windows"

    [[YASM.download]]
    sha256 = "5efbeef10baed759f617ea354e7318846a708022890a413b54803f17edad87d8"
    url = "https://github.com/JuliaBinaryWrappers/YASM_jll.jl/releases/download/YASM-v1.3.0+1/YASM.v1.3.0.i686-w64-mingw32.tar.gz"
[[YASM]]
arch = "powerpc64le"
git-tree-sha1 = "ac8b135dd23b099f9948c2a9d5b731a5c4d03f5b"
libc = "glibc"
os = "linux"

    [[YASM.download]]
    sha256 = "49125ca14127ea0530947f12d2e790cbd3fd178c3ecfbb48f9edf09d8fb83514"
    url = "https://github.com/JuliaBinaryWrappers/YASM_jll.jl/releases/download/YASM-v1.3.0+1/YASM.v1.3.0.powerpc64le-linux-gnu.tar.gz"
[[YASM]]
arch = "x86_64"
git-tree-sha1 = "510624b6a96b2466776726d2a4246d03d2478e8a"
os = "macos"

    [[YASM.download]]
    sha256 = "17c60c3c31ff29920b292c9a6da05d730ff819f81978f6d1218a4ad8e26e18c0"
    url = "https://github.com/JuliaBinaryWrappers/YASM_jll.jl/releases/download/YASM-v1.3.0+1/YASM.v1.3.0.x86_64-apple-darwin.tar.gz"
[[YASM]]
arch = "x86_64"
git-tree-sha1 = "8b25bdb71169ca2bad5260447d70f15d4509a7f2"
libc = "glibc"
os = "linux"

    [[YASM.download]]
    sha256 = "dadf917af7c1cb9aed49e0559d021ea9f9cda7b96a4b526820a96b05084cd500"
    url = "https://github.com/JuliaBinaryWrappers/YASM_jll.jl/releases/download/YASM-v1.3.0+1/YASM.v1.3.0.x86_64-linux-gnu.tar.gz"
[[YASM]]
arch = "x86_64"
git-tree-sha1 = "ec50e52bfb6106c95daebd7da612a9e42715fdb7"
libc = "musl"
os = "linux"

    [[YASM.download]]
    sha256 = "38b3d8ddbb9ad094b56a316bf74ff2c8d08b4687511cc96d96848561516f4ad2"
    url = "https://github.com/JuliaBinaryWrappers/YASM_jll.jl/releases/download/YASM-v1.3.0+1/YASM.v1.3.0.x86_64-linux-musl.tar.gz"
[[YASM]]
arch = "x86_64"
git-tree-sha1 = "d8728bf57a18cd10237e7c51448eefbce2e09f2e"
os = "freebsd"

    [[YASM.download]]
    sha256 = "1d7fedca504612360673a4b3509ed2292f86e55db32652fc3a19ff6b633711f5"
    url = "https://github.com/JuliaBinaryWrappers/YASM_jll.jl/releases/download/YASM-v1.3.0+1/YASM.v1.3.0.x86_64-unknown-freebsd.tar.gz"
[[YASM]]
arch = "x86_64"
git-tree-sha1 = "92005f853d9bfb4c9a2240afdc9b924d88306289"
os = "windows"

    [[YASM.download]]
    sha256 = "836eb96971783b2f4ce342c594f165de09f4c54954624c12d46a16ea0ac57645"
    url = "https://github.com/JuliaBinaryWrappers/YASM_jll.jl/releases/download/YASM-v1.3.0+1/YASM.v1.3.0.x86_64-w64-mingw32.tar.gz"
