[[YASM]]
arch = "aarch64"
git-tree-sha1 = "7e445ca91aeeda11a7b129cfa8554ad2881ee081"
os = "macos"

    [[YASM.download]]
    sha256 = "12b0f1dcbb9714dd5012c95f2d68a705733149cefd33946380d279de931e4880"
    url = "https://github.com/JuliaBinaryWrappers/YASM_jll.jl/releases/download/YASM-v1.3.0+0/YASM.v1.3.0.aarch64-apple-darwin.tar.gz"
[[YASM]]
arch = "aarch64"
git-tree-sha1 = "b392d9a52188c34303afdb739c290ef1c981e5df"
libc = "glibc"
os = "linux"

    [[YASM.download]]
    sha256 = "96b3620a260984a09598e9f334989a2be49357c31cd25bc49259616d7c490fbd"
    url = "https://github.com/JuliaBinaryWrappers/YASM_jll.jl/releases/download/YASM-v1.3.0+0/YASM.v1.3.0.aarch64-linux-gnu.tar.gz"
[[YASM]]
arch = "aarch64"
git-tree-sha1 = "36f5705f4169248ae56e30a64a4cb53eaa87bee8"
libc = "musl"
os = "linux"

    [[YASM.download]]
    sha256 = "1d4a24e280ca6d01c92cd9dc83c970eff6c993b81500526efe09d534a2e4daaa"
    url = "https://github.com/JuliaBinaryWrappers/YASM_jll.jl/releases/download/YASM-v1.3.0+0/YASM.v1.3.0.aarch64-linux-musl.tar.gz"
[[YASM]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "81fb27799ca68f1615e2bce30f1f96abe7844fc9"
libc = "glibc"
os = "linux"

    [[YASM.download]]
    sha256 = "9c336290363be293a383c98ed8c519062a820d72b58de1b2704c571f0e575841"
    url = "https://github.com/JuliaBinaryWrappers/YASM_jll.jl/releases/download/YASM-v1.3.0+0/YASM.v1.3.0.armv6l-linux-gnueabihf.tar.gz"
[[YASM]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "dd115deeb9b3210899a228489b9c8973d9ed8d9a"
libc = "musl"
os = "linux"

    [[YASM.download]]
    sha256 = "32d83c197d7d6e16731907ab2e899e2b8cbdf01ee06bb01a1c51eb3581c4d9e5"
    url = "https://github.com/JuliaBinaryWrappers/YASM_jll.jl/releases/download/YASM-v1.3.0+0/YASM.v1.3.0.armv6l-linux-musleabihf.tar.gz"
[[YASM]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "d1a4c2027959bdd000921570268c6510ac4f4bd7"
libc = "glibc"
os = "linux"

    [[YASM.download]]
    sha256 = "c710271ea27d16bdbcaddac986ea9c4d9fc6bf13de78f6a5a4834dcf2b436f3b"
    url = "https://github.com/JuliaBinaryWrappers/YASM_jll.jl/releases/download/YASM-v1.3.0+0/YASM.v1.3.0.armv7l-linux-gnueabihf.tar.gz"
[[YASM]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "4e1c128b410f175a5fcdb8308f96d398097f1b04"
libc = "musl"
os = "linux"

    [[YASM.download]]
    sha256 = "ba932a974236cd079b3e91f4726083fd331e532171713ae9ad53b1848d9fae05"
    url = "https://github.com/JuliaBinaryWrappers/YASM_jll.jl/releases/download/YASM-v1.3.0+0/YASM.v1.3.0.armv7l-linux-musleabihf.tar.gz"
[[YASM]]
arch = "i686"
git-tree-sha1 = "d9a935fdf7226a8e8117787421229aa9de124009"
libc = "glibc"
os = "linux"

    [[YASM.download]]
    sha256 = "b8529d609623d00d47a6dfaf796c2f27aa944ccf18157177d9a7e79e1676add3"
    url = "https://github.com/JuliaBinaryWrappers/YASM_jll.jl/releases/download/YASM-v1.3.0+0/YASM.v1.3.0.i686-linux-gnu.tar.gz"
[[YASM]]
arch = "i686"
git-tree-sha1 = "ed3cb066e29677df2f66cffc83a6734789acdeec"
libc = "musl"
os = "linux"

    [[YASM.download]]
    sha256 = "7c7bd3a4a5b3bd3b0bc52a39b71633bc129abe853ee0b20b0ad36407b91be019"
    url = "https://github.com/JuliaBinaryWrappers/YASM_jll.jl/releases/download/YASM-v1.3.0+0/YASM.v1.3.0.i686-linux-musl.tar.gz"
[[YASM]]
arch = "i686"
git-tree-sha1 = "e36e2293c482e71ff0ed123af5b37228be916324"
os = "windows"

    [[YASM.download]]
    sha256 = "586f661c4bfbaddda2f54436f4097b974b7d934045a5e399bdd033e53ea4fbad"
    url = "https://github.com/JuliaBinaryWrappers/YASM_jll.jl/releases/download/YASM-v1.3.0+0/YASM.v1.3.0.i686-w64-mingw32.tar.gz"
[[YASM]]
arch = "powerpc64le"
git-tree-sha1 = "9ef1378391e40505a60b94b5431842b46fa74002"
libc = "glibc"
os = "linux"

    [[YASM.download]]
    sha256 = "b2b98e81c372d56b39824ac4f1aa1f13f93767bfd5c31697aec277b60f391a7b"
    url = "https://github.com/JuliaBinaryWrappers/YASM_jll.jl/releases/download/YASM-v1.3.0+0/YASM.v1.3.0.powerpc64le-linux-gnu.tar.gz"
[[YASM]]
arch = "x86_64"
git-tree-sha1 = "b7e21b041fc78983f129e401f4f5d4d89d5c3818"
os = "macos"

    [[YASM.download]]
    sha256 = "dd5da996431a5f6315a017e12a12e50a2add1863e87bfeac2b7d1f70cba74947"
    url = "https://github.com/JuliaBinaryWrappers/YASM_jll.jl/releases/download/YASM-v1.3.0+0/YASM.v1.3.0.x86_64-apple-darwin.tar.gz"
[[YASM]]
arch = "x86_64"
git-tree-sha1 = "cd2e639eea1c5299fdfa1226d576a08c795b6bfe"
libc = "glibc"
os = "linux"

    [[YASM.download]]
    sha256 = "8cd176d101e0d6a36af6eb7487e88eae6312d65db28ed49567d1e1a18ef2bc91"
    url = "https://github.com/JuliaBinaryWrappers/YASM_jll.jl/releases/download/YASM-v1.3.0+0/YASM.v1.3.0.x86_64-linux-gnu.tar.gz"
[[YASM]]
arch = "x86_64"
git-tree-sha1 = "2edaae63d16c7d1c3ef7b1ae05f251ca7d1e68a1"
libc = "musl"
os = "linux"

    [[YASM.download]]
    sha256 = "990de40c3dbba1eef1f6370da90e8189b625b362fba1e0aec3dc008874118594"
    url = "https://github.com/JuliaBinaryWrappers/YASM_jll.jl/releases/download/YASM-v1.3.0+0/YASM.v1.3.0.x86_64-linux-musl.tar.gz"
[[YASM]]
arch = "x86_64"
git-tree-sha1 = "02f45783ef3aeed87251c3cde54ff1499ec0df3f"
os = "freebsd"

    [[YASM.download]]
    sha256 = "3c51f003f78deb20076777fc944a627b91d1e76ab4acbde0d91743c0d7e84913"
    url = "https://github.com/JuliaBinaryWrappers/YASM_jll.jl/releases/download/YASM-v1.3.0+0/YASM.v1.3.0.x86_64-unknown-freebsd.tar.gz"
[[YASM]]
arch = "x86_64"
git-tree-sha1 = "79a88b8f983d4be866c3e56370ab9c9b7efcd1b6"
os = "windows"

    [[YASM.download]]
    sha256 = "0d173382a717a53262b2e197062d1c31e6f5f547b77dded352764435ff2a6ab3"
    url = "https://github.com/JuliaBinaryWrappers/YASM_jll.jl/releases/download/YASM-v1.3.0+0/YASM.v1.3.0.x86_64-w64-mingw32.tar.gz"
